### PR TITLE
Resolved deprecation warnings of Guard 2.0 

### PR DESCRIPTION
**Pull request by raeno**
Upgraded to Guard 2.0 version following the guideline described at https://github.com/guard/guard/wiki/Upgrading-to-Guard-2.0#changes-in-guardguard

### CODE REVIEW

**Comment by yld** [comment]
+ 1 but notifications do not work work now with guard 2.12.2

**Comment by jessekempf** [comment]
@gvillalta99: do you suppose you could merge this PR and push an updated version of this gem up onto rubygems? I want to upgrade the quality control toolchain we use at work to use Guard v2, but we can't give up guard-reek to do that and so we're kinda stuck.

**Comment by gvillalta99** [comment]
Thank you @raeno !
@yld and @jessekempf bumping the version.
I'm not working with this gem anymore, if any of you would like to take care of this I would pass the ownership of this to you.

**Comment by jessekempf** [comment]
@gvillalta99: My day job needs this gem to work, so I could take over ownership.

**Comment by gvillalta99** [comment]
Great @jessekempf, I'm giving it to you.

**Comment by gvillalta99** [comment]
@jessekempf, are you using your fork? Does it has any changes?
Because github is complaining that I can't transfer it to you while you have  a repository with the same name.
Let's work to merge your changes on this repo, then you delete your fork and I transfer this repo to you.
@jessekempf are you ok with this plan?

**Pull request merged**
