### PR TITLE
Rewrite to work with latest guard

### PR DESCRIPTION
**Pull request by grantspeelman**
* Also updated to use rspec 3
* Took ideas from guard-rubocop

@gvillalta99 Would you consider merging this ?

### CODE REVIEW

**Comment by gvillalta99** [comment]
Thank you @grantspeelman.
I'm not maintaining this anymore and if you are interested I can move the ownership of this project to you.

**Comment by grantspeelman** [comment]
@gvillalta99 sure I'll be happy to take over maintainance, what do I have to do?

**Comment by gvillalta99** [comment]
@grantspeelman I need your rubygems.org associated email so I could set you as an owner, then I will transfer the github repo to your github account. Is that ok?

**Comment by grantspeelman** [comment]
@gvillalta99 My rubygems email address is grantspeelman@gmail.com

**Comment by gvillalta99** [comment]
@grantspeelman done:
https://rubygems.org/gems/guard-reek

**Comment by gvillalta99** [comment]
@grantspeelman I've sent an request to transfer this repo to you.
Please accept it so you can manage it freely.
Thank you! :+1:

**Comment by grantspeelman** [comment]
@gvillalta99 
Did not get a transfer request but already managed to release a new version from https://github.com/my-grocery-price-book/guard-reek

Maybe you can add above your README that the repo has moved to https://github.com/my-grocery-price-book/guard-reek

**Pull request merged**
